ignores:
  # used on release
  - '@changesets/changelog-github'
  # internal packages
  - '@crackle-private/bootstrap'
  - '@crackle/cli'
  - '@crackle/core'
  - '@crackle/router' # broken code that needs to be updated in packages/router/src/entries/routes.ts
  # testing
  - vitest
  - '~utils'
  # aliases used by the web module
  - __THE_ENTRY
  - __BROWSER_PAGE_MODULES
  - __NODE_PAGE_MODULES
