packages:
  - 'packages/*'
  - 'fixtures/*'
  - fixtures/braid-design-system # Braid monorepo deps (required for integration tests)
  - fixtures/braid-design-system/integration # Braid's integration tests
  - fixtures/braid-design-system/packages/braid-design-system
  - bootstrap
  - scripts
  - test-utils
  - tests
neverBuiltDependencies:
  - sku
patchedDependencies:
  sync-dependencies@1.0.4: patches/sync-dependencies@1.0.4.patch
peerDependencyRules:
  ignoreMissing:
    - jest
    - sku
overrides:
  '@braid-design-system/source.macro': latest
  braid>@crackle/cli: workspace:*
  ink>@types/react: ^18
