name: Checkout & Install
description: ''

inputs:
  token:
    description: GitHub token
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    # The correct order is:
    # 1. actions/checkout (so package.json can be read by actions/setup-node)
    # 2. pnpm/action-setup (so the cache is available to actions/setup-node)
    # 3. actions/setup-node

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Restore Cache
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash

    - name: Save Cache
      uses: actions/cache/save@v3
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: '**/node_modules'
        key: ${{ steps.cache.outputs.cache-primary-key }}
