name: Init

on:
  workflow_call:

jobs:
  init:
    name: Checkout & Install
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # The correct order is:
      # 1. actions/checkout (so package.json can be read by actions/setup-node)
      # 2. pnpm/action-setup (so the cache is available to actions/setup-node)
      # 3. actions/setup-node

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
