name: Release

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Install
        uses: seek-oss/crackle/.github/actions/init@master
        with:
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Create Release PR / Publish to npm
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEEK_OSS_CI_NPM_TOKEN }}
