name: Snapshot

on: push

env:
  CI: true

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    environment: snapshot
    steps:
      - name: Checkout & Install
        uses: seek-oss/crackle/.github/actions/init@master

      - name: Publish
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm prepare-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEEK_OSS_CI_NPM_TOKEN }}
