name: Validate

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Set up pnpm and install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm fix
          pnpm build

      - name: Setup fixtures
        run: pnpm dev-fixtures

      - name: Lint
        run: pnpm lint

      - name: Install Browsers
        run: pnpm playwright install chromium

      - name: Test
        run: pnpm test
