name: Validate

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: |
          yarn fix
          yarn build

      - name: Setup fixtures
        run: yarn dev-fixtures

      - name: Lint
        run: yarn lint

      - name: Install Browsers
        run: yarn playwright install chromium

      - name: Test
        run: yarn test
