name: Validate

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup fixtures
        run: yarn dev-fixtures

      - name: Lint
        run: yarn lint

      # Temporarily suspend tests until everything is migrated to non-monorepo

      # - name: Install Browsers
      #   run: yarn playwright install chromium

      # - name: Test
      #   run: yarn test
